import {useEffect,useState} from "react";


import Sidebar from "../components/Sidebar";
import Navbar from "../components/Navbar";


import {
getTransfers,
updateTransfer,
getTransferAudit
} from "../api/transfers";


import "../styles/Planner.css";



function Planner(){



const [approvals,setApprovals]=useState([]);



const [audit,setAudit]=useState(null);

const [showAudit,setShowAudit]=useState(false);







const loadTransfers=async()=>{


try{


const response =
await getTransfers();


setApprovals(response.data);



}
catch(error){


console.log(error);


}


};









const updateStatus=async(id,status)=>{


try{


await updateTransfer(

id,

{
status:status
}

);



alert(
"Transfer "+status
);



loadTransfers();



}
catch(error){


console.log(error);


}


};









const viewAudit=async(id)=>{


try{


const response =
await getTransferAudit(id);



setAudit(response.data);



setShowAudit(true);



}
catch(error){


console.log(error);


alert("Audit Loading Failed");


}


};









useEffect(()=>{


loadTransfers();


},[]);







return(


<div className="dashboard">


<Sidebar/>




<div className="main-content">


<Navbar/>





<h2 className="page-title">

Planner Approval Center

</h2>









<div className="planner-cards">



<div className="planner-card">

<h4>

Pending Approval

</h4>

<h2>

{
approvals.filter(
item=>item.status==="Pending"
).length
}

</h2>

</div>







<div className="planner-card">

<h4>

Approved Today

</h4>

<h2>

{
approvals.filter(
item=>item.status==="Approved"
).length
}

</h2>

</div>







<div className="planner-card">

<h4>

Rejected

</h4>

<h2>

{
approvals.filter(
item=>item.status==="Rejected"
).length
}

</h2>

</div>







<div className="planner-card">

<h4>

Total Transfers

</h4>

<h2>

{approvals.length}

</h2>

</div>




</div>









{

approvals.map((item)=>(



<div

className="approval-box"

key={item.id}

>




<div className="approval-header">


<h3>

TR-{item.id}

</h3>



<span className="confidence">

AI

</span>



</div>









<div className="approval-grid">



<div>

<p>

<b>From</b>

</p>

<p>

{item.fromLocation}

</p>

</div>







<div>

<p>

<b>To</b>

</p>

<p>

{item.toLocation}

</p>

</div>







<div>

<p>

<b>SKU</b>

</p>

<p>

{item.sku}

</p>

</div>







<div>

<p>

<b>Quantity</b>

</p>

<p>

{item.quantity}

</p>

</div>







<div>

<p>

<b>Transfer Cost</b>

</p>

<p>

₹ {item.cost}

</p>

</div>







<div>

<p>

<b>Expected Profit</b>

</p>

<p>

₹ {item.profit}

</p>

</div>




</div>









<div className="reason">


<h4>

AI Recommendation

</h4>


<p>

Inventory optimization recommendation generated by AI Agent

</p>


</div>









<div className="planner-buttons">



<button

className="approve-btn"

onClick={()=>
updateStatus(
item.id,
"Approved"
)
}

>

Approve

</button>







<button

className="reject-btn"

onClick={()=>
updateStatus(
item.id,
"Rejected"
)
}

>

Reject

</button>








<button

className="audit-btn"

onClick={()=>
viewAudit(item.id)
}

>

View Audit

</button>





</div>






</div>



))


}









{
showAudit && audit && (


<div className="modal">


<div className="modal-content">



<h2>

Transfer Audit

</h2>





<p>

<b>Transfer ID:</b>

{audit.transferId}

</p>





<p>

<b>Agent:</b>

{audit.agentName}

</p>





<p>

<b>Action:</b>

{audit.action}

</p>





<p>

<b>SKU:</b>

{audit.sku}

</p>





<p>

<b>Quantity:</b>

{audit.quantity}

</p>





<p>

<b>Decision:</b>

{audit.decision}

</p>





<p>

<b>Status:</b>

{audit.status}

</p>








<button

className="reject"

onClick={()=>{
setShowAudit(false);
setAudit(null);
}}

>

Close

</button>




</div>


</div>


)

}





</div>


</div>


);



}


export default Planner;